### ISSUE TITLE
Can this library be used in production projects?

### ISSUE THREAD

**Issue by wwhai** [Lensual/go-libav#1]
# Can this library be used in production projects? The requirement is simple: just pull the stream and then push the stream.

**Comment by Lensual** [comment]
Not recommend. It's not full tested.
It's used for me. I have no time to complete and full test it.
You can try it. Issue and PR is welecom.

Though it's not recommend, but I hope it's helpful for you.
If you are in China, you can contact with me by WeChat: Lensual
